const axios = require("axios");
const { error: logError } = require("../../utils/logger.js");
const AI_BASE_URL = process.env.AI_BASE_URL || "http://127.0.0.1:5001";
const RESPONSE_API_URL = `${AI_BASE_URL}/api/classify`; // Endpoint for response generated by Transformer

async function processCategory(query) {
    try {
        const pythonResponse = await axios.post(RESPONSE_API_URL, { query });
        const { category } = pythonResponse.data;
        return { category };
    } catch (error) {
        logError("Category processing failed", error.message);
        return "Sorry, I couldn't process that query.";;
    }
}

module.exports = { processCategory };
