const axios = require("axios");
const AI_BASE_URL = process.env.AI_BASE_URL || "http://127.0.0.1:5001";
const RESPONSE_API_URL = `${AI_BASE_URL}/api/predict`; // Endpoint for response generated by Transformer

async function processQuery(query) {
    try {
        const pythonResponse = await axios.post(RESPONSE_API_URL, { query });
        const { category, response } = pythonResponse.data;
        return { category, response };
    } catch (error) {
        console.error("Error in transformer model:", error);
        return "Sorry, I couldn't process that query.";
    }
}

module.exports = { processQuery };
