const axios = require("axios");
const { error: logError } = require("../../utils/logger.js");
const AI_BASE_URL = process.env.AI_BASE_URL || "http://127.0.0.1:5001";
const RESPONSE_API_URL = `${AI_BASE_URL}/api/translate`; // Endpoint for response generated by Transformer

async function translateResponse(query) {
    try {
        const pythonResponse = await axios.post(RESPONSE_API_URL, { sentence: query });
        const { translation } = pythonResponse.data;
        return { translation };
    } catch (error) {
        logError("Error in translation model", error.message);
        return "Sorry, I couldn't translate the response.";
    }
}

module.exports = { translateResponse };
